### ISSUE TITLE
Crops couse tps to go downhill, for some reason (ships performance issues somehow)

### ISSUE THREAD

**Issue by animation-is-always-taken** [Minecraft-Ships/ShipsForCore#86]
when a player places any crop (wheet, carrots, potatos, you know what i'm talking about) for some reazon the server tps go downhill, yes this is related to Ships becouse when i remove the plugin everything works like normal, when i place the plugin crops bassicaly crash the server

To Reproduce the bug

1. Minecraft 1.18.2
2. Platform: git-Purpur-1632 (MC: 1.18.2) & git-Paper-372 (MC: 1.18.2)
3. Ships version: 6.0.0, beta 14.5

the logs have nothing related to the bug, but i have timings
https://timings.aikar.co/?id=8b20acab97a54e19b8818a89ed18234c
https://timings.aikar.co/?id=7184ea21128f4b0983f27f0c4e6a8b85 i was doing nothing for... a while here
https://timings.aikar.co/?id=67bb7c80bb814b829532764aafd31c11

**Comment by mosemister** [comment]
Hi. Mind showing me your config file. I have a feeling on what's going on and if it's what I think it is, it's patched in the Dev versions (however they have a smaller issue that I'm working on)

**Comment by animation-is-always-taken** [comment]
> Hi. Mind showing me your config file. I have a feeling on what's going on and if it's what I think it is, it's patched in the Dev versions (however they have a smaller issue that I'm working on)

here you go
[Config.txt](https://github.com/Minecraft-Ships/ShipsForCore/files/9274126/Config.txt) i had to change the file to txt becouse github wouldn't let me upload it
[BlockList.txt](https://github.com/Minecraft-Ships/ShipsForCore/files/9274125/BlockList.txt)

**Comment by mosemister** [comment]
Ah ok. I see the problem.

Your running an older config value that is only there for compatibility with plugins that don't expect it.

```yaml
  BlockFinder:
    Default: ships:blockfinder_ships_six
```

In particular it's this value. 

The newer version of it doesn't cause any lag.

```yaml
  BlockFinder:
    Default: ships:blockfinder_ships_six_async
```

Here is your whole config with the change 


```yaml
# test
Advanced:
  Movement:
    Default: ships:movement_ships_six
    Stack:
      Limit: 20
      Delay: 1
      DelayUnit: MINECRAFT_TICKS
  BlockFinder:
    Default: ships:blockfinder_ships_six_async
    Track: 4000
    Stack:
      Delay: 1
      DelayUnit: MINECRAFT_TICKS
      Limit: 7
  EntityFinder:
    Stack:
      Limit: 75
Auto:
  EOT:
    Speed: 2
    Delay: 1
    DelayUnit: SECONDS
    Enabled: false
  Falling:
    Speed: 1
    Delay: 1
    DelayUnit: MINUTES
    Enabled: false
Bar:
  Visible: false
Movement:
  Requirements:
    Check:
      Max:
        BlockType: false
Structure:
  Update:
    Auto: true
    Click: false
  Prevent:
    Explosion: true
Update:
  Enabled: true
Sign:
  Licence:
    Fourth: ''
  Move:
    Speed: 2
Login:
  Command: ''
Event:
  OnLoad:
    Failed:
      DeleteFile: false
```
